from pathlib import Path
import sys,json,html,hashlib,datetime
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(ROOT/'bin'))
from mb_catalogo import CSS,gerar
from mb_entregas_registro import registrar
folder=ROOT/'00_PARA-VOCE/260916_plataforma';folder.mkdir(parents=True,exist_ok=True)
baseline=json.loads((HERE/'baseline.json').read_text(encoding='utf-8'))
e=html.escape
findings=[
('Pendência antiga reaparece','O painel solicitava aprovar o tema claro, embora o HANDOFF já registrasse aprovação e publicação.','Leitura de bloco vigente implementada. O histórico continua preservado.','bin/mb-relatorio-vivo.py'),
('A IA recebe o projeto errado','O hook identificava a central ao receber o caminho do Pets, antes de procurar o marcador do subprojeto.','Busca pelo marcador mais próximo implementada e testada.','bin/mb-contexto.py'),
('Cota sem prova parece saudável','Erros de autenticação, indisponibilidade e limite passavam pelo teste de medição da rota automática.','Correção independente com testes antes/depois; estados sem prova deixam de ser chamados saudáveis.','apps/automations/automations.py'),
('Entregas disputam atenção',f'A pasta humana tinha {baseline["inbox_file_count"]} arquivos, {len(baseline["inbox_directories"])} pastas e {len(baseline["inbox_loose_files"])} arquivos soltos na medição inicial.','Uma entrada fixa reúne destinos registrados; legado fica recolhido e pesquisável. Endereços antigos preservados.','evidence/260916_plataforma/baseline.json'),
('A mesma conversa recebe regras diferentes','O hook exigia alinhamento de todo prompt e a skill dispensava o processo em perguntas simples.','Triagem comum conectada ao hook; profundidade opcional separada de qualidade e permissão.','bin/mb_triagem.py'),
('Caminho existe, mas exige trabalho manual','O relatório criava botão para copiar comandos, mas caminhos HTML podiam ficar só como texto.','Entrada oferece abrir arquivo, abrir pasta e copiar destino completo; identidade comum padroniza a resposta.','bin/mb_catalogo.py'),
('Escrita concorrente pode perder atualização','Motor e widget leem e substituem o mesmo JSON de orçamento. Substituição atômica não resolve a disputa entre duas leituras.','Risco encontrado no código; ocorrência real não demonstrada. Correção própria no backlog, sem mexer agora nos dois escritores.','apps/ia-quota-widget/widget_app/budget_status.py')]
rows=''.join(f'<tr><td><b>{e(t)}</b></td><td>{e(p)}</td><td>{e(a)}<br><a href="{(ROOT/s).as_uri()}">Fonte</a></td></tr>' for t,p,a,s in findings)
back=json.loads((ROOT/'dados/plataforma-backlog.json').read_text(encoding='utf-8'))
road=''.join(f'<tr><td>{e(x["id"])} · {e(x["titulo"])}</td><td>{e(x["estado"].replace("_"," "))}</td><td>{e(x["criterio"])}</td></tr>' for x in back['itens'])
doc=f'''<!doctype html><html lang="pt-BR" data-tema="escuro"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MEGABRAIN · análise e evolução</title><style>{CSS}table{{width:100%;border-collapse:collapse;font-size:14px}}th,td{{text-align:left;vertical-align:top;padding:14px 10px;border-bottom:1px solid var(--linha)}}th{{color:var(--fraco)}}.scroll{{overflow-x:auto}}section{{margin:35px 0}}td:first-child{{min-width:170px}}td{{min-width:220px}}.flow{{display:flex;flex-wrap:wrap;gap:9px;margin:18px 0}}.flow span{{padding:8px 12px;border:1px solid var(--linha);border-radius:6px}}</style><body><main><header><div><div class="eyebrow">MEGABRAIN / ANÁLISE E EVOLUÇÃO · 16 SET 2026</div><h1>Uma entrada. Trabalho rastreável.</h1></div><button id="theme">Tema: escuro</button></header><p>A estrutura tem recursos úteis, mas cobra de você o trabalho de descobrir qual documento, sessão e painel está valendo. A primeira melhoria organiza o acesso e corrige falhas de contexto; a consolidação dos aplicativos fica dividida em etapas verificáveis.</p><div class="actions"><a class="button primary" href="../INICIO.html">Voltar ao início</a><a class="button" href="{(ROOT/'motor/referencias/260916_plataforma-contrato.md').as_uri()}">Contrato de pastas e respostas</a><a class="button" href="{(ROOT/'dados/plataforma-backlog.json').as_uri()}">Plano de evolução</a></div>
<section class="focus"><h2>O que mudou agora</h2><p>Entrada fixa com busca, filtros, projeto/sessão, próximo passo e destinos que abrem ou copiam. O aplicativo existente ganhou acesso a essa entrada e um controle de sensibilidade. O mecanismo de contexto passou a usar a triagem comum.</p><p><b>Preservado:</b> endereços antigos, aplicativos existentes, conteúdo de outras sessões e tema claro/escuro. <b>Custo:</b> catálogo gerado precisa ser atualizado; regra por palavras exige conferência da IA e pode errar. A interface não torna antigas entregas automaticamente aprovadas.</p></section>
<section><h2>Diagnóstico humano e da IA</h2><p>Fatos do disco e reproduções locais, comparados com decisões e reclamações registradas. A revisão independente examinou o código sem depender da interpretação do implementador.</p><div class="scroll"><table><thead><tr><th>Problema</th><th>Evidência e efeito</th><th>Tratamento</th></tr></thead><tbody>{rows}</tbody></table></div></section>
<section><h2>Como a esteira decide</h2><div class="flow"><span>Pedido + conversa</span><span>→ Contexto e sinais</span><span>→ Etapas pertinentes</span><span>→ Produção e revisão</span><span>→ Verificação e destino</span></div><p>Um “valeu” atravessa a triagem e recebe resposta curta. “Faz um PDF” continua sendo entrega mesmo tendo poucas palavras. “Publica” exige interpretar escopo e autorização; “não publique” não autoriza a publicação. “Sim” precisa herdar o contexto, sem transformar confirmação isolada em permissão nova.</p><p><b>Enxuta:</b> etapas necessárias. <b>Equilibrada:</b> acrescenta explicação de hipóteses relevantes. <b>Criteriosa:</b> pode acrescentar outra lente e alternativas quando houver decisão real. O piso de qualidade permanece igual nos três níveis.</p><p>O controle no aplicativo grava a preferência real, lida na próxima triagem. No HTML estático, a explicação não altera configuração. A integração automática depende do cliente chamar o hook; identidade sincronizada é orientação persistente, não prova de que toda sessão ativa já a carregou.</p></section>
<section><h2>Organização fixa, sem quebrar endereços</h2><p>Você entra por <code>00_PARA-VOCE/INICIO.html</code>. Novas entregas usam uma pasta por tarefa, com entrada principal e recursos. Provas, logs e backup ficam em <code>evidence/</code>. O relatório técnico mantém seu endereço. A IA consulta registro e fontes; o usuário consulta o catálogo.</p><p>A migração física do acervo antigo não foi executada: há trabalhos concorrentes e consumidores dos caminhos existentes. Agrupar a apresentação já permite encontrar os arquivos; mover tudo agora acrescentaria risco sem prova de benefício. O lote futuro exige inventário de links e uma reversão testada.</p></section>
<section><h2>Planejamento da plataforma</h2><p>O backlog abaixo é a fonte única deste plano. Sem novo widget para cada problema: primeiro definir dono do dado, tarefa do usuário e como a função entra na navegação existente.</p><div class="scroll"><table><thead><tr><th>Etapa</th><th>Estado</th><th>Critério de saída</th></tr></thead><tbody>{road}</tbody></table></div></section>
<section><h2>O que aproveitei do chat do Claude</h2><p>Li o histórico salvo da tarefa “Megabrain user experience analysis”, o plano e sua revisão. A incorporação usa os arquivos como evidência e proposta; o texto digitado, mas não enviado, no print não foi tratado como decisão.</p><p><b>Incorporado:</b> bússola Começou/Agora/Etapa no catálogo, ligada a resumos explícitos da sessão; preservação da regra de resposta já gravada pelo Claude; correção da pendência antiga no painel; planejamento por etapas com prova e reversão. Os modelos de entrega e de estado vigente ficam na estrutura canônica.</p><p><b>Corrigido na análise:</b> a afirmação “não há medidor de contexto” não se sustenta no disco atual. O script já registra <code>evento: contexto_injetado</code>, e a contagem independente encontrou 177 eventos nos cinco logs mais recentes. Isso prova execução histórica, mas não que o acionamento automático esteja configurado em cada cliente hoje. O diagnóstico detalhado está vinculado abaixo.</p><p><b>Mantido como experimento:</b> ocultar pastas pode melhorar o Explorer, mas o próprio teste do Claude mostra que algumas buscas passam a ignorar arquivos. Antes de aplicar, o piloto precisa comparar os mesmos resultados nos clientes afetados e testar a restauração de atributos. Projetos não foram classificados como abandonados pela idade do ESTADO. Permissão para git e arquivamento de outros projetos permanece separada.</p><div class="actions"><a class="button" href="{(ROOT/'00_PARA-VOCE/260916_ux-megabrain/260916_PLANO-UX-MEGABRAIN.html').as_uri()}">Plano original do Claude</a><a class="button" href="{(HERE/'contexto-medicao.md').as_uri()}">Verificação do medidor</a><a class="button" href="{(ROOT/'motor/modelos/260916_ENTREGA.json').as_uri()}">Modelo de entrega</a><a class="button" href="{(ROOT/'motor/modelos/260916_ESTADO-ATUAL.md').as_uri()}">Modelo de estado</a></div></section>
<section><h2>O que prova melhora — e o que ainda falta medir</h2><p>A situação inicial teve 307 testes do motor, com duas falhas preexistentes registradas. A verificação desta rodada acrescenta casos para triagem, caminhos, entrada, subprojetos e saúde de cota, além de interações no navegador e no aplicativo. Resultados finais ficam no recibo de verificação abaixo.</p><p><b>Não medido:</b> tempo real que você leva para localizar algo, satisfação no uso prolongado, comportamento de todas as sessões já abertas e todos os aplicativos. Não há porcentagem inventada de ganho nem promessa de zero piora global. O próximo teste humano compara tarefas equivalentes: abrir a entrega certa, recuperar uma decisão e mudar a sensibilidade.</p><div class="actions"><a class="button" href="{(HERE/'verificacao-final.json').as_uri()}">Provas da rodada</a><a class="button" href="{(HERE/'auditoria-independente.md').as_uri()}">Revisão independente</a><a class="button" href="{(HERE/'baseline.json').as_uri()}">Situação inicial</a><a class="button" href="{(HERE/'REVERTER.md').as_uri()}">Como reverter</a></div></section>
<footer>Inspeção das frentes principais: protocolo, identidade, contexto, estado, entregas, catálogo, orçamento e navegação. Não equivale a auditar cada função de cada aplicativo. Fontes locais verificadas nesta sessão; o plano V6 foi revisado em <code>260916_175608_306d11cb</code>, sem confundir revisão textual com código executado.</footer></main><script>(()=>{{const r=document.documentElement,b=document.getElementById('theme');function set(t){{r.dataset.tema=t;b.textContent='Tema: '+t}}try{{set(localStorage.getItem('megabrain.pop.tema')==='claro'?'claro':'escuro')}}catch(e){{}}b.onclick=()=>{{const t=r.dataset.tema==='claro'?'escuro':'claro';set(t);try{{localStorage.setItem('megabrain.pop.tema',t)}}catch(e){{}}}}}})()</script></body></html>'''
out=folder/'260916_ANALISE.html';out.write_text(doc,encoding='utf-8')
registrar(ROOT,{'id':'plataforma-260916','titulo':'Organização e evolução do MEGABRAIN','tarefa':'Arquitetura, experiência humana e uso pela IA','sessao':'Codex · 260916 · 2242','pedido_inicial':'Organizar o MEGABRAIN para você e para a IA, sem perder qualidade.','pedido_atual':'Integrar as contribuições verificadas da análise do Claude.','etapa':'Entrega implementada; validação final registrada nas provas.','estado':'em_revisao','pasta':str(folder),'arquivo':str(out),'proxima_acao':'Abrir a análise e consultar o que foi implementado, medido e planejado.'})
print(gerar(ROOT))
